name: Build Marp Slides

on:
  push:
    paths:
      - '**/slides/**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Marp CLI
      run: npm install -g @marp-team/marp-cli

    - name: Convert all .md slides to PDF
      shell: bash
      run: |
        shopt -s globstar
        for file in **/slides/*.md; do
          # Skip any files in a slides/old/ directory
          if [[ "$file" == */slides/old/* ]]; then
            continue
          fi

          output="${file%.md}.pdf"
          echo "📝 Converting: $file → $output"

          # Ensure asset paths resolve by calling Marp from the file's folder
          dir=$(dirname "$file")
          base=$(basename "$file")
          (cd "$dir" && marp "$base" --pdf "$(basename "${output}")" --allow-local-files)
        done

    - name: Upload all PDFs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: marp-pdfs
        path: '**/slides/*.pdf'
